import React,{useCallback,useEffect,useMemo,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Search, MapPin, Navigation, RefreshCw, X, Wind, Droplets, Thermometer, Gauge, Sun, Sunrise, Sunset, Leaf, CloudOff, LoaderCircle, Cloud, CloudSun, CloudFog, CloudRain, Snowflake, CloudSnow, CloudLightning, Moon, Check, ChevronRight} from 'lucide-react';
import './styles.css';
import type {AirQualityData,LocationData,SearchResult,WeatherData} from './types';
import {aqiInfo, currentHourIndex,dayName,fetchAirQuality,fetchWeather,formatHour,gradientFor,reverseGeocode,searchLocations,sunTime,uvInfo,weatherDescription} from './weather';

const bg='/src/weather-bg.jpg';
function WeatherIcon({code,isDay=true,size=24}:{code:number;isDay?:boolean;size?:number}){
 const C=code===0?(isDay?Sun:Moon):code<=2?CloudSun:code===3?Cloud:code<=48?CloudFog:code<=67?CloudRain:code<=77?Snowflake:code<=86?CloudSnow:CloudLightning;
 return <C size={size} strokeWidth={1.8} aria-hidden="true"/>;
}

function Stat({icon:Icon,label,value}:{icon:React.ElementType;label:string;value:string}){return <div className="stat"><Icon size={17}/><div><span>{label}</span><strong>{value}</strong></div></div>}
function Hourly({w,isDay}:{w:WeatherData['hourly'];isDay:boolean}){const i=currentHourIndex(w.time); return <section className="panel"><h3>HOURLY</h3><div className="hour-scroll">{w.time.slice(i,i+24).map((t,j)=><div className={'hour '+(!j?'now':'')} key={t}><b>{!j?'Now':formatHour(t)}</b><span className="weather-emoji">{<WeatherIcon code={w.weathercode[i+j]} isDay={isDay} size={23}/>}</span><strong>{Math.round(w.temperature_2m[i+j])}°</strong></div>)}</div></section>}
function Details({aqi,uv,humidity,feels,pressure,sunrise,sunset}:{aqi:number|null;uv:number;humidity:number;feels:number;pressure:number;sunrise:string;sunset:string}){const ai=aqi==null?null:aqiInfo(aqi), ui=uvInfo(uv); return <section><h3 className="section-title">AIR &amp; DETAILS</h3><div className="details-grid">
 <Detail icon={Leaf} label="AIR QUALITY" value={aqi==null?'--':String(Math.round(aqi))} sub={ai?.[0]} subColor={ai?.[1]}/><Detail icon={Sun} label="UV INDEX" value={String(Math.round(uv))} sub={ui[0]} subColor={ui[1]}/>
 <Detail icon={Droplets} label="HUMIDITY" value={`${humidity}%`} sub={humidity<30?'Dry':humidity<60?'Comfortable':'Humid'}/><Detail icon={Thermometer} label="FEELS LIKE" value={`${Math.round(feels)}°C`} sub={feels<0?'Freezing':feels<10?'Cold':feels<20?'Cool':feels<30?'Warm':'Hot'}/>
 <Detail icon={Sunrise} label="SUNRISE" value={sunTime(sunrise)}/><Detail icon={Sunset} label="SUNSET" value={sunTime(sunset)}/><Detail icon={Gauge} label="PRESSURE" value={`${Math.round(pressure)} hPa`} sub={pressure<1000?'Low pressure':pressure>1020?'High pressure':'Normal'} full/>
 </div></section>}
function Detail({icon:Icon,label,value,sub,subColor,full}:{icon:React.ElementType;label:string;value:string;sub?:string;subColor?:string;full?:boolean}){return <div className={'detail '+(full?'full':'')}><div className="detail-head"><Icon size={15}/><span>{label}</span></div><strong>{value}</strong>{sub&&<small style={{color:subColor}}>{sub}</small>}</div>}
function Daily({d}:{d:WeatherData['daily']}){return <section className="panel"><h3>7-DAY FORECAST</h3>{d.time.map((day,i)=><div className="day-row" key={day}><b>{dayName(day)}</b><span>{<WeatherIcon code={d.weathercode[i]} isDay={true} size={21}/>} {d.precipitation_probability_max[i]>20&&<em>{d.precipitation_probability_max[i]}%</em>}</span><div><strong>{Math.round(d.temperature_2m_max[i])}°</strong><small>{Math.round(d.temperature_2m_min[i])}°</small></div></div>)}</section>}
function SearchModal({open,onClose,onSelect,onGPS,isManual}:{open:boolean;onClose:()=>void;onSelect:(l:LocationData)=>void;onGPS:()=>void;isManual:boolean}){const [q,setQ]=useState('');const [results,setResults]=useState<SearchResult[]>([]);const [loading,setLoading]=useState(false);const [error,setError]=useState('');useEffect(()=>{if(!open){setQ('');setResults([]);setError('');return;} if(q.trim().length<2){setResults([]);setLoading(false);return;}const id=setTimeout(async()=>{setLoading(true);setError('');try{setResults(await searchLocations(q.trim()));}catch{setError('Could not search locations. Check your connection.');}finally{setLoading(false);}},400);return()=>clearTimeout(id)},[q,open]); if(!open)return null; return <div className="modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><div className="modal"><header><h2>Search Location</h2><button onClick={onClose}><X/></button></header><div className="search-box"><Search size={18}/><input autoFocus value={q} onChange={e=>setQ(e.target.value)} placeholder="City name…"/>{q&&<button onClick={()=>setQ('')}><X size={17}/></button>}</div><button className="gps-row" onClick={onGPS}><span><Navigation/></span><div><b>Use My Location</b><small>{isManual?'Switch back to GPS':'Currently using GPS'}</small></div>{!isManual&&<span className="check"><Check size={18}/></span>}</button>{q&&<div className="results-label">{loading?'Searching…':results.length?'Results':error?'Error':'No results'}</div>}{loading&&<LoaderCircle className="spin"/>}{error&&!loading&&<div className="empty"><CloudOff/><p>{error}</p></div>}{!loading&&!error&&q.length>1&&!results.length&&<div className="empty"><Search/><p>No locations found</p></div>}{results.map((r,i)=>{const city=r.address.city||r.address.town||r.address.village||r.address.county||r.display_name.split(',')[0];return <button className="result" key={`${r.lat}-${r.lon}-${i}`} onClick={()=>{onSelect({latitude:+r.lat,longitude:+r.lon,city,country:r.address.country_code?.toUpperCase()||r.address.country||''});setQ('');onClose()}}><span><MapPin/></span><div><b>{city}</b><small>{r.display_name}</small></div><ChevronRight size={18}/></button>})}</div></div>}

function App(){const [location,setLocation]=useState<LocationData|null>(null);const [manual,setManual]=useState(false);const [permission,setPermission]=useState<'loading'|'granted'|'denied'>('loading');const [locationError,setLocationError]=useState('');const [weather,setWeather]=useState<WeatherData|null>(null);const [aq,setAq]=useState<AirQualityData|null>(null);const [loading,setLoading]=useState(false);const [error,setError]=useState('');const [searchOpen,setSearchOpen]=useState(false);
 const getGPS=useCallback(async()=>{setPermission('loading');setLocationError('');if(!navigator.geolocation){setPermission('denied');setLocationError('Geolocation is not supported by this browser.');return;}navigator.geolocation.getCurrentPosition(async p=>{const city=await reverseGeocode(p.coords.latitude,p.coords.longitude);setLocation({latitude:p.coords.latitude,longitude:p.coords.longitude,...city});setManual(false);setPermission('granted');},e=>{setPermission('denied');setLocationError(e.message||'Location permission denied.');},{timeout:10000,enableHighAccuracy:false});},[]);
 useEffect(()=>{getGPS()},[getGPS]);
 const load=useCallback(async()=>{if(!location)return;setLoading(true);setError('');try{const [w,a]=await Promise.all([fetchWeather(location),fetchAirQuality(location).catch(()=>null)]);setWeather(w);setAq(a);}catch(e){setError(e instanceof Error?e.message:'Could not load weather.');}finally{setLoading(false)}},[location]);
 useEffect(()=>{load()},[load]);
 const current=useMemo(()=>{if(!weather)return null;const i=currentHourIndex(weather.hourly.time);return {i,feels:weather.hourly.apparent_temperature[i]??weather.current_weather.temperature,humidity:weather.hourly.relativehumidity_2m[i]??0,uv:weather.hourly.uv_index[i]??0,pressure:weather.hourly.surface_pressure[i]??1013,aqi:aq?aq.hourly.us_aqi[currentHourIndex(aq.hourly.time)]??null:null}},[weather,aq]);
 const gradient=weather?gradientFor(weather.current_weather.weathercode,weather.current_weather.is_day===1):['#0a0f1e','#0d1624'];
 if(permission==='loading'&&!location)return <State icon={<LoaderCircle className="spin"/>} title="Loading weather..."/>;
 if(permission==='denied'&&!location)return <State icon={<Navigation/>} title="Location Required" message={locationError||'Allow location access or search for a city.'} action="Allow Location" onAction={getGPS} onSearch={()=>setSearchOpen(true)} />;
 if(error&&!weather)return <State icon={<CloudOff/>} title="No Weather Data" message="Could not load weather. Check your connection." action="Try Again" onAction={load} onSearch={()=>setSearchOpen(true)}/>;
 if(!weather||!location||!current)return null;
 const date=new Date().toLocaleDateString(undefined,{weekday:'long',month:'long',day:'numeric'});
 return <div className="app" style={{'--g1':gradient[0],'--g2':gradient[1]} as React.CSSProperties}><div className="backdrop" style={{backgroundImage:`url(${bg})`}}/><div className="overlay"/><main><div className="top"><button className="location" onClick={()=>setSearchOpen(true)}><MapPin size={16}/><b>{location.city}{location.country?`, ${location.country}`:''}</b></button><button className="icon-btn" onClick={load} title="Refresh"><RefreshCw size={17} className={loading?'spin':''}/></button></div><p className="date">{date}</p><div className="hero"><div className="hero-icon">{<WeatherIcon code={weather.current_weather.weathercode} isDay={weather.current_weather.is_day===1} size={76}/>}</div><div className="temp">{Math.round(weather.current_weather.temperature)}°<span>C</span></div><div className="desc">{weatherDescription(weather.current_weather.weathercode)}</div></div><div className="stats"><Stat icon={Thermometer} label="Feels Like" value={`${Math.round(current.feels)}°C`}/><Stat icon={Droplets} label="Humidity" value={`${current.humidity}%`}/><Stat icon={Wind} label="Wind" value={`${Math.round(weather.current_weather.windspeed)} km/h`}/></div><Hourly w={weather.hourly} isDay={weather.current_weather.is_day===1}/><Details aqi={current.aqi} uv={current.uv} humidity={current.humidity} feels={current.feels} pressure={current.pressure} sunrise={weather.daily.sunrise[0]} sunset={weather.daily.sunset[0]}/><Daily d={weather.daily}/><footer>Weather data by Open-Meteo · Location search by OpenStreetMap Nominatim</footer></main><SearchModal open={searchOpen} onClose={()=>setSearchOpen(false)} onSelect={l=>{setLocation(l);setManual(true)}} onGPS={()=>{getGPS();setSearchOpen(false)}} isManual={manual}/></div>}
function State({icon,title,message,action,onAction,onSearch}:{icon:React.ReactNode;title:string;message?:string;action?:string;onAction?:()=>void;onSearch?:()=>void}){return <div className="state" style={{backgroundImage:`linear-gradient(#0a0f1eea,#0d1624ea),url(${bg})`}}><div>{icon}</div><h1>{title}</h1>{message&&<p>{message}</p>}{action&&<button onClick={onAction}>{action}</button>}{onSearch&&<button className="secondary" onClick={onSearch}>Search a city instead</button>}</div>}

createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
